# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Different Components of the Application
services:

  web-api:
    container_name: ${SERVER_CONTAINER}
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - appdata:/app/volume
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: python /app/manage.py runserver 0.0.0.0:${SERVER_PORT}
    networks:
      - backend
      - frontend
    depends_on:
      - db

  web-ui:
    build:
      context: DMarketing-web-main
      dockerfile: Dockerfile
    ports:
      - "2001:8080" # Map the exposed port 2001 on the container to port 8080 on the host machine
    networks:
      - frontend
    depends_on:
      - web-api

  # Database Service (Mysql)
  db:
    container_name: ${DB_CONTAINER}
    image: mysql:5.7
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  appdata:
  db-data:

networks:
  backend:
  frontend: