# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Different Components of the Application
services:

  # Database Service (Mysql)
  app-db:
    container_name: theater-platform-db
    image: mysql:5.7
    ports:
      - "2003:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - ./docker-volumes/db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3

  app-backend:
    container_name: theater-platform-django-api-server
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '2004:8000'
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 8000"
    restart: on-failure
    environment:
      DEBUG: '1'
      DB_HOST: theater-platform-db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_USER_PW}
    networks:
      - backend
      - frontend
    depends_on:
      app-db:
        condition: service_healthy

  app-frontend:
    container_name: theater-platform-web-ui
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "2005:8080"
    networks:
      - frontend

volumes:
  appdata:
  db-data:

networks:
  backend:
  frontend: