# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Different Components of the Application
services:

  # Database Service (Mysql)
  app-db:
    container_name: theater-platform-db
    image: mysql:5.7
    ports:
      - '2003:3306'
    restart: always
    environment:
      MYSQL_DATABASE: theater_platform
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - ./volumes/db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: 'mysqladmin ping -h theater-platform-db -P 3306 -u ${DB_USER} --password="${DB_USER_PW}"'
      timeout: 10s
      retries: 3

  app-backend:
    container_name: theater-platform-django-api-server
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '2004:8000'
    command: >
      sh -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 8000'
    restart: on-failure
    environment:
      DEBUG: '1'
      DB_HOST: theater-platform-db
      DB_PORT: 3306
      DB_NAME: theater_platform
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_USER_PW}
    volumes:
      - ./volumes/app-data:/app/appdata
    networks:
      - backend
      - frontend
    depends_on:
      app-db:
        condition: service_healthy

  app-frontend:
    container_name: theater-platform-web-ui
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '2005:8080'
    networks:
      - frontend

volumes:
  db-data:
  app-data:

networks:
  backend:
  frontend: