# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Different Components of the Application
services:

  # Database Service (Mysql)
  app-db:
    image: mysql
    container_name: ${DB_HOST}
    ports:
      - '2003:${DB_PORT}'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_USER:          ${DB_USER}
      MYSQL_PASSWORD:      ${DB_USER_PW}
    volumes:
      - ./volumes/db-data:/var/lib/mysql 
      - ./scripts/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: 'mysqladmin ping -h ${DB_HOST} -P ${DB_PORT} -u root --password="${DB_ROOT_PW}"'
      timeout: 10s
      retries: 3

  # Server Backend Service (Django)
  app-backend:
    container_name: ${API_HOST}
    ports:
      - '2004:${API_PORT}'
    build:
      context: backend
      dockerfile: Dockerfile
    command: >
      sh -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${API_PORT}'
    environment:
      DEBUG: '1'
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_USER_PW}
    volumes:
      - ./volumes/app-data:/app/appdata
    networks:
      - backend
      - frontend
    healthcheck:
      test: 'wget -nv -t1 --spider http://localhost:${API_PORT}/healthcheck/ || exit 1'
      timeout: 10s
      retries: 3
    depends_on:
      app-db:
        condition: service_healthy

  # Server Frontend Service (Vue.js)
  app-frontend:
    container_name: ${UI_HOST}
    ports:
      - '2005:${UI_PORT}'
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    depends_on:
      app-db:
        condition: service_healthy
      app-backend:
        condition: service_healthy

volumes:
  db-data:
  app-data:

networks:
  backend:
  frontend:
