# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Different Components of the Application
services:

  web-api:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - appdata:/app/volume
    ports:
      - "8000:8000"
    command: python /app/manage.py runserver 0.0.0.0:8000
    networks:
      - backend
      - frontend

  web-ui:
    build:
      context: DMarketing-web-main
      dockerfile: Dockerfile
    ports:
      - "2001:8080" # Map the exposed port 2001 on the container to port 8080 on the host machine
    networks:
      - frontend

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: theater_platform
      MYSQL_USER: theater_admin
      MYSQL_PASSWORD: theater_platform2021
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  appdata:
  db-data:

networks:
  backend:
  frontend: